name: ci-workflows

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# This is to avoid running multiple actions when a PR is updated repeatedly. See
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sanity:
    uses: ./.github/workflows/sanity.yml
