name: ci-workflows

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# This is to avoid running multiple actions when a PR is updated repeatedly. See
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3.0.5
        with:
          path: node_modules
          key: v1-npm-deps-sanity-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            v1-npm-deps-sanity-
            v1-npm-deps-
      - name: Cache eslint
        uses: actions/cache@v3.0.5
        with:
          path: .eslintcache
          key: v1-eslint-${{ github.sha }}
          restore-keys: v1-eslint-
      - name: Install dependencies
        run: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
      - name: ESLint
        run: npm run lint
      - name: Run type checks
        run: npx tsc
      - uses: ./.github/workflows/sanity.yml
