name: npm-publish

# on:
#   release:
#     types: [published]
on:
  pull_request:
    branches:
      - main

jobs:
  sanity:
    uses: ./.github/workflows/sanity.yml

  npm-publish:
    runs-on: ubuntu-latest

    environment: production

    env:
      CENTRAL_SERVICES_BASE_URL: ${{ secrets.CENTRAL_SERVICES_BASE_URL }}
      STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
      USE_MOCK_SERVER: ${{ secrets.USE_MOCK_SERVER }}

    steps:
      # - name: Publish if version has been updated
      #   uses: pascalgn/npm-publish-action@1.3.9
      #   with: # All of theses inputs are optional
      #     tag_name: "v%s"
      #     tag_message: "v%s"
      #     create_tag: "true"
      #     commit_pattern: "^Release (\\S+)"
      #     workspace: "."
      #     publish_command: "yarn"
      #     publish_args: "--non-interactive --access public"
      #   env: # More info about the environment variables in the README
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # You need to set this in your repo settings

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          check-version: True
          dry-run: True
