name: Update dependencies
on:
  push:
    branches:
      - main

env:
  lockfile: pnpm-lock.yaml
  node_version: "18"
  pnpm_version: "8"

jobs:
  update_dependencies:
    name: Node.js
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Check if cache key exists
        uses: actions/cache/restore@v4
        id: cache_exists
        with:
          lookup-only: true
          path: node_modules
          key: ${{ runner.os }}-node-deps-${{ hashFiles(env.lockfile) }}

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        id: pnpm-install

      - name: Set up Node.js
        uses: actions/setup-node@v4
        if: steps.cache_exists.outputs.cache-hit != 'true'
        with:
          node-version: ${{ env.node_version }}

      - name: Install dependencies
        if: steps.cache_exists.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Store dependencies in cache
        uses: actions/cache/save@v4
        if: steps.cache_exists.outputs.cache-hit != 'true'
        with:
          path: node_modules
          key: ${{ runner.os }}-node-deps-${{ hashFiles(env.lockfile) }}
